apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oh-staff.fullname" . }}-configmap
  namespace: oh-staff{{ .Values.django.env.run_env }}
  labels:
    {{- include "oh-staff.labels" . | nindent 4 }}
data:
  DJANGO_RUN_ENV: {{ .Values.django.env.run_env }}
  DJANGO_DEBUG: {{ .Values.django.env.debug | quote }}
  DJANGO_LOG_LEVEL: {{ .Values.django.env.log_level }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.django.env.allowed_hosts | quote }}
  DJANGO_CSRF_TRUSTED_ORIGINS: {{ range .Values.django.env.csrf_trusted_origins }}{{ . | quote }}{{ end }}
  DJANGO_ARK_MINTER: {{ .Values.django.env.ark_minter }}
  DJANGO_DB_BACKEND: {{ .Values.django.env.db_backend }}
  DJANGO_DB_HOST: {{ .Values.django.env.db_host }}
  DJANGO_DB_PORT: {{ .Values.django.env.db_port | quote }}
  DJANGO_DB_NAME: {{ .Values.django.env.db_name }}
  DJANGO_DB_USER: {{ .Values.django.env.db_user }}
  DJANGO_OH_FILE_SOURCE: {{ .Values.django.env.oh_file_source }}
  DJANGO_OH_MEDIA_ROOT: {{ .Values.django.env.oh_media_root }}
  DJANGO_OH_MASTERSLZ: {{ .Values.django.env.oh_masterslz }}
  DJANGO_OH_STATIC: {{ .Values.django.env.oh_static }}
  DJANGO_OH_WOWZA: {{ .Values.django.env.oh_wowza }}
  