apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "oh-staff.fullname" . }}-pvc-ohwowza
  namespace: oh-staff{{ .Values.django.env.run_env }}
spec:
  accessModes:
    - {{ .Values.persistentVolumes.ohwowza.access }}
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.persistentVolumes.ohwowza.storage }}
  volumeName: {{ include "oh-staff.fullname" . }}-pv-ohwowza