{{ if not .Values.django.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oh-staff.fullname" . }}-secrets
  namespace: oh-staff{{ .Values.django.env.run_env }}
  labels:
{{ include "oh-staff.fullname" . | indent 4 }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ randAlphaNum 20 | b64enc | quote }}
  DJANGO_DB_PASSWORD: {{ .Values.django.env.db_password | b64enc | quote }}
{{ end }}