# Generated by Django 4.1.3 on 2023-03-02 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import oh_staff_ui.models


class Migration(migrations.Migration):

    replaces = [('oh_staff_ui', '0001_initial'), ('oh_staff_ui', '0002_alter_itemstatus_options_itemtype'), ('oh_staff_ui', '0003_projectitem'), ('oh_staff_ui', '0004_authoritysource_language'), ('oh_staff_ui', '0005_nametype_name'), ('oh_staff_ui', '0006_subjecttype_subject'), ('oh_staff_ui', '0007_altidtype_alttitletype_alttitle_altid'), ('oh_staff_ui', '0008_descriptiontype_publishertype_publisher_description'), ('oh_staff_ui', '0009_alter_projectitem_create_date_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40)),
                ('status_description', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Item statuses',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='AuthoritySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=256)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.authoritysource')),
            ],
        ),
        migrations.CreateModel(
            name='NameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.authoritysource')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.nametype')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.authoritysource')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.subjecttype')),
            ],
        ),
        migrations.CreateModel(
            name='AltIdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AltTitleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AltTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=512)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.authoritysource')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.alttitletype')),
            ],
        ),
        migrations.CreateModel(
            name='AltId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.authoritysource')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.altidtype')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PublisherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.authoritysource')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.publishertype')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1024)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.authoritysource')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.descriptiontype')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ark', models.CharField(max_length=40)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateField(default=django.utils.timezone.now)),
                ('sequence', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=256)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.projectitem')),
                ('status', models.ForeignKey(default=oh_staff_ui.models.get_default_status, on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.itemstatus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.itemtype')),
            ],
        ),
    ]
