# Generated by Django 4.1.3 on 2022-12-03 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemstatus',
            options={'verbose_name_plural': 'Item statuses'},
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.itemtype')),
            ],
        ),
    ]
