# Generated by Django 4.1.3 on 2023-04-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0002_alter_description_value'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='altid',
            index=models.Index(fields=['value'], name='oh_staff_ui_value_674bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='altidtype',
            index=models.Index(fields=['type'], name='oh_staff_ui_type_55ea50_idx'),
        ),
        migrations.AddIndex(
            model_name='alttitle',
            index=models.Index(fields=['value'], name='oh_staff_ui_value_49adba_idx'),
        ),
        migrations.AddIndex(
            model_name='alttitletype',
            index=models.Index(fields=['type'], name='oh_staff_ui_type_495f72_idx'),
        ),
        migrations.AddIndex(
            model_name='authoritysource',
            index=models.Index(fields=['source'], name='oh_staff_ui_source_e21368_idx'),
        ),
        migrations.AddIndex(
            model_name='copyright',
            index=models.Index(fields=['value'], name='oh_staff_ui_value_c8b9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='copyrighttype',
            index=models.Index(fields=['type'], name='oh_staff_ui_type_fd899f_idx'),
        ),
        migrations.AddIndex(
            model_name='date',
            index=models.Index(fields=['value'], name='oh_staff_ui_value_fe4d63_idx'),
        ),
        migrations.AddIndex(
            model_name='datetype',
            index=models.Index(fields=['type'], name='oh_staff_ui_type_94927b_idx'),
        ),
        migrations.AddIndex(
            model_name='descriptiontype',
            index=models.Index(fields=['type'], name='oh_staff_ui_type_07c83d_idx'),
        ),
        migrations.AddIndex(
            model_name='format',
            index=models.Index(fields=['value'], name='oh_staff_ui_value_3bbd1a_idx'),
        ),
        migrations.AddIndex(
            model_name='itemstatus',
            index=models.Index(fields=['status'], name='oh_staff_ui_status_f6909b_idx'),
        ),
        migrations.AddIndex(
            model_name='itemtype',
            index=models.Index(fields=['type'], name='oh_staff_ui_type_9e3abb_idx'),
        ),
        migrations.AddIndex(
            model_name='name',
            index=models.Index(fields=['value'], name='oh_staff_ui_value_777996_idx'),
        ),
        migrations.AddIndex(
            model_name='nametype',
            index=models.Index(fields=['type'], name='oh_staff_ui_type_ebb93a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['ark'], name='oh_staff_ui_ark_7b0f11_idx'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['title'], name='oh_staff_ui_title_4c0c92_idx'),
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['value'], name='oh_staff_ui_value_d92de9_idx'),
        ),
        migrations.AddIndex(
            model_name='publishertype',
            index=models.Index(fields=['type'], name='oh_staff_ui_type_491714_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['value'], name='oh_staff_ui_value_b9d12a_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcetype',
            index=models.Index(fields=['type'], name='oh_staff_ui_type_7b4e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['value'], name='oh_staff_ui_value_f25c84_idx'),
        ),
        migrations.AddIndex(
            model_name='subjecttype',
            index=models.Index(fields=['type'], name='oh_staff_ui_type_67d614_idx'),
        ),
    ]
