# Generated by Django 4.1.3 on 2023-04-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0004_mediafile_mediafiletype_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itemcopyrightusage',
            constraint=models.UniqueConstraint(fields=('item', 'value', 'type'), name='copyright_value_type_unique'),
        ),
        migrations.AddConstraint(
            model_name='itemlanguageusage',
            constraint=models.UniqueConstraint(fields=('item', 'value'), name='language_value_unique'),
        ),
        migrations.AddConstraint(
            model_name='itemnameusage',
            constraint=models.UniqueConstraint(fields=('item', 'value', 'type'), name='name_value_type_unique'),
        ),
        migrations.AddConstraint(
            model_name='itempublisherusage',
            constraint=models.UniqueConstraint(fields=('item', 'value', 'type'), name='publisher_value_type_unique'),
        ),
        migrations.AddConstraint(
            model_name='itemresourceusage',
            constraint=models.UniqueConstraint(fields=('item', 'value', 'type'), name='resource_value_type_unique'),
        ),
        migrations.AddConstraint(
            model_name='itemsubjectusage',
            constraint=models.UniqueConstraint(fields=('item', 'value', 'type'), name='subject_value_type_unique'),
        ),
    ]
