# Generated by Django 4.1.3 on 2023-04-21 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0005_itemcopyrightusage_copyright_value_type_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='coverage',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='last_modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='relation',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
