# Generated by Django 4.1.3 on 2023-04-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0006_alter_projectitem_coverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='original_file_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
