# Generated by Django 4.1.3 on 2023-05-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0007_mediafile_original_file_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mediafiletype',
            name='oh_staff_ui_file_ty_2526fb_idx',
        ),
        migrations.AddField(
            model_name='mediafiletype',
            name='file_code',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mediafiletype',
            name='file_type',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
