# Generated by Django 4.1.3 on 2023-02-22 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0007_altidtype_alttitletype_alttitle_altid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PublisherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.authoritysource')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.publishertype')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1024)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.authoritysource')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.descriptiontype')),
            ],
        ),
    ]
