# Generated by Django 4.1.3 on 2023-05-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0008_remove_mediafiletype_oh_staff_ui_file_ty_2526fb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
