# Generated by Django 4.1.3 on 2023-05-09 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0009_mediafile_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
