# Generated by Django 4.1.3 on 2023-03-03 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0001_squashed_0009_alter_projectitem_create_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altid',
            name='type',
        ),
        migrations.RemoveField(
            model_name='alttitle',
            name='type',
        ),
        migrations.RemoveField(
            model_name='description',
            name='type',
        ),
        migrations.RemoveField(
            model_name='name',
            name='type',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='type',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='type',
        ),
        migrations.AlterField(
            model_name='altid',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.authoritysource'),
        ),
        migrations.AlterField(
            model_name='alttitle',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.authoritysource'),
        ),
        migrations.AlterField(
            model_name='description',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.authoritysource'),
        ),
        migrations.AlterField(
            model_name='language',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.authoritysource'),
        ),
        migrations.AlterField(
            model_name='name',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.authoritysource'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.authoritysource'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.authoritysource'),
        ),
        migrations.CreateModel(
            name='ItemSubjectUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.projectitem')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.subject')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.subjecttype')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPublisherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.projectitem')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.publisher')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.publishertype')),
            ],
        ),
        migrations.CreateModel(
            name='ItemNameUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.projectitem')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.name')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.nametype')),
            ],
        ),
        migrations.CreateModel(
            name='ItemLanguageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.projectitem')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.language')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDescriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.description')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.projectitem')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.descriptiontype')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAltTitleUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.alttitle')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.projectitem')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.alttitletype')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAltIdUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.altid')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.projectitem')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.altidtype')),
            ],
        ),
    ]
