# Generated by Django 4.1.3 on 2023-03-08 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0010_remove_altid_type_remove_alttitle_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.authoritysource')),
            ],
        ),
        migrations.CreateModel(
            name='CopyrightType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCopyrightUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.projectitem')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.copyright')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.copyrighttype')),
            ],
        ),
    ]
