# Generated by Django 4.1.3 on 2023-05-22 22:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0010_alter_mediafile_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFileError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_name', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.projectitem')),
            ],
        ),
    ]
