# Generated by Django 4.1.3 on 2023-03-09 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0011_copyright_copyrighttype_itemcopyrightusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcopyrightusage',
            old_name='publisher',
            new_name='copyright',
        ),
    ]
