# Generated by Django 5.2.10 on 2026-01-30 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0011_mediafileerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oh_staff_ui.projectitem'),
        ),
    ]
