# Generated by Django 4.1.3 on 2023-03-10 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0012_rename_publisher_itemcopyrightusage_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='coverage',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1024)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.projectitem')),
            ],
        ),
    ]
