# Generated by Django 5.2.13 on 2026-05-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0012_alter_description_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafiletype',
            name='file_code',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
