# Generated by Django 4.1.3 on 2023-03-21 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0013_projectitem_coverage_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.authoritysource')),
            ],
        ),
        migrations.CreateModel(
            name='ItemResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.projectitem')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.resource')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.resourcetype')),
            ],
        ),
    ]
