# Generated by Django 4.1.3 on 2023-03-24 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oh_staff_ui', '0014_resourcetype_resource_itemresourceusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemalttitleusage',
            name='alt_title',
        ),
        migrations.RemoveField(
            model_name='itemalttitleusage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemalttitleusage',
            name='type',
        ),
        migrations.RemoveField(
            model_name='itemdescriptionusage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='itemdescriptionusage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemdescriptionusage',
            name='type',
        ),
        migrations.RemoveField(
            model_name='altid',
            name='source',
        ),
        migrations.RemoveField(
            model_name='alttitle',
            name='source',
        ),
        migrations.RemoveField(
            model_name='description',
            name='source',
        ),
        migrations.AddField(
            model_name='altid',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.projectitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alttitle',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.projectitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.projectitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectitem',
            name='relation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='ItemAltIdUsage',
        ),
        migrations.DeleteModel(
            name='ItemAltTitleUsage',
        ),
        migrations.DeleteModel(
            name='ItemDescriptionUsage',
        ),
        migrations.AddField(
            model_name='date',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oh_staff_ui.projectitem'),
        ),
    ]
